(scl 6)
(seed (in "/dev/urandom" (rd 8)))
(load "@lib/frac.l")
(load "@lib/simul.l")

(load "1-atom-atom.l")
(msg 1)
(load "2-atom-list.l")
(msg 1)

(load "3-list-atom.l")
(msg 1)

(load "4-list-list.l")
(msg 1)

(load "5-atom-atom-atom.l")
(msg 1)

(load "6-atom-atom-list.l")
(msg 1)

(load "7-list-atom-atom.l")
(msg 1)

(load "8-list-atom-list.l")
(msg 1)

(load "9-list-list-atom.l")
(msg 1)

(load "10-list-list-list.l")
(msg 1)

(load "11-atom-atom-atom-atom.l")
(msg 1)

(load "12-atom-atom-atom-list.l")
(msg 1)

(load "13-list-atom-atom-atom.l")
(msg 1)

(load "14-list-atom-atom-list.l")
(msg 1)

(load "15-list-list-atom-atom.l")
(msg 1)

(load "16-list-list-atom-list.l")
(msg 1)

(load "17-list-list-list-list.l")
(msg 1)

(load "18-list-list-atom-atom-list.l")
(msg 1)

(msg 'gorlansky-OK)
